/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-22 17:51:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.sinhvien.CV;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/TuyenDung/KHOALUAN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TuyenDungSV/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1649851804832L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"bg\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/layout/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("    <div style=\"height:70px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("    	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("            <div class=\"col-4 cv-left\" >\r\n");
      out.write("                <div class=\"d-flex\">\r\n");
      out.write("                    <img class=\"avatar\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/image/2227baef989555cb0c84.jpg\" style=\"display: block;\">\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"text-align: center;\">\r\n");
      out.write("                     <p style=\"font-size: 17px;font-weight: bold; margin: 15px 0 5px 0; margin-top: 15px; margin-bottom: 5px;\">DƯƠNG THỊ KIỀU TRANG</p>\r\n");
      out.write("                     <p style=\"font-size: 14px;\">WEB DEVELOPER</p> \r\n");
      out.write("                     <hr>\r\n");
      out.write("                </div>  \r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"contact-icon col-2\"><i class=\"fas fa-calendar-alt\"></i></div>\r\n");
      out.write("                        <div class=\"contact-info col-10\">13/06/2000</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"contact-icon col-2\"><i class=\"fas fa-user\"></i></div>\r\n");
      out.write("                        <div class=\"contact-info col-10\">Nữ</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"contact-icon col-2\"><i class=\"fas fa-phone-alt\"></i></div>\r\n");
      out.write("                        <div class=\"contact-info col-10\">0944510246</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"contact-icon col-2\"><i class=\"fas fa-envelope\"></i></div>\r\n");
      out.write("                        <div class=\"contact-info col-10\">trang@gmail.com</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"contact-icon col-2\"><i class=\"fas fa-map-marker-alt\"></i></div>\r\n");
      out.write("                        <div class=\"contact-info col-10\">An Cựu, Huế</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cv-left-item\">\r\n");
      out.write("                    <h5 style=\"margin-bottom: 20px;\">MỤC TIÊU NGHỀ NGHIỆP</h5>\r\n");
      out.write("                    <ul class=\"cv-right-item-mota\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            Ngắn hạn: Được tham gia đào tạo tại công ty, tích lũy thêm nhiều kinh nghiệm, \r\n");
      out.write("                            rèn luyện thêm nhiều kỹ năng xử lí công việc. Có công việc ổn định.\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            Dài hạn: Trở thành nhân viên ưu tú, có cơ hội làm việc tại nước ngoài, đạt được mức lương cao.\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul> \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cv-left-item\">\r\n");
      out.write("                    <h5 style=\"margin-bottom: 20px;\">KỸ NĂNG</h5>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div>HTML</div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div style=\"height: 10px; background-color: white;\">\r\n");
      out.write("                                <div style=\"height: 10px;width: 50%;background-color: #548CA8;\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mt-2\">\r\n");
      out.write("                        <div>HTML</div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div style=\"height: 10px; background-color: white;\">\r\n");
      out.write("                                <div style=\"height: 10px;width: 40%;background-color: #548CA8;\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mt-2\">\r\n");
      out.write("                        <div>HTML</div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div style=\"height: 10px; background-color: white;\">\r\n");
      out.write("                                <div style=\"height: 10px;width: 80%;background-color: #548CA8;\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cv-left-item\">\r\n");
      out.write("                    <h5 style=\"margin-bottom: 20px;\">SỞ THÍCH</h5>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>Đọc sách</li>\r\n");
      out.write("                        <li>Nghe nhạc</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-8 cv-right\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"cv-right-item\">\r\n");
      out.write("                    <div class=\"cv-right-item-name\"><h5 >HỌC VẤN</h5></div>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div><b> Trường Đại học Khoa học Huế</b></div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <div class=\"row mb-2\"    >\r\n");
      out.write("                                        <div class=\"col-8\">\r\n");
      out.write("                                            Sinh viên khoa Công nghệ thông tin\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            08/2018 - Hiện tại\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <ul class=\"cv-right-item-mota\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            Mô tả một chút nha hihiMô tả một chút nha hihiMô tả một \r\n");
      out.write("                                            chút nha hihiMô tả một chút nha hihiMô tả một chút nha hihiMô tả \r\n");
      out.write("                                            một chút nha hihiMô tả một chút nha hihi\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            Mô tả một chút nha hihi\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul> \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cv-right-item\">\r\n");
      out.write("                    <div class=\"cv-right-item-name\"><h5 >KINH NGHIỆM LÀM VIỆC</h5></div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div><b> Trường Đại học Khoa học Huế</b></div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div class=\"row mb-2\"    >\r\n");
      out.write("                                    <div class=\"col-8\">\r\n");
      out.write("                                        Sinh viên khoa Công nghệ thông tin\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-4\">\r\n");
      out.write("                                        08/2018 - Hiện tại\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <ul class=\"cv-right-item-mota\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        Mô tả một chút nha hihiMô tả một chút nha hihiMô tả một \r\n");
      out.write("                                        chút nha hihiMô tả một chút nha hihiMô tả một chút nha hihiMô tả \r\n");
      out.write("                                        một chút nha hihiMô tả một chút nha hihi\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        Mô tả một chút nha hihi\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul> \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cv-right-item\">\r\n");
      out.write("                    <div class=\"cv-right-item-name\"><h5 >HOẠT ĐỘNG</h5></div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div><b> Trường Đại học Khoa học Huế</b></div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div class=\"row mb-2\"    >\r\n");
      out.write("                                    <div class=\"col-8\">\r\n");
      out.write("                                        Sinh viên khoa Công nghệ thông tin\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-4\">\r\n");
      out.write("                                        08/2018 - Hiện tại\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <ul class=\"cv-right-item-mota\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        Mô tả một chút nha hihiMô tả một chút nha hihiMô tả một \r\n");
      out.write("                                        chút nha hihiMô tả một chút nha hihiMô tả một chút nha hihiMô tả \r\n");
      out.write("                                        một chút nha hihiMô tả một chút nha hihi\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        Mô tả một chút nha hihi\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul> \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cv-right-item\">\r\n");
      out.write("                    <div class=\"cv-right-item-name\"><h5 >CHỨNG CHỈ</h5></div>\r\n");
      out.write("                    <div class=\"row mb-2\" style=\"margin-left: 20px;\"   >\r\n");
      out.write("                        <div class=\"col-8 chungchi-name\">\r\n");
      out.write("                            N4 Tiếng Nhật\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-4\">\r\n");
      out.write("                            2018\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/layout/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/pages/sinhvien/CV/show.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/pages/sinhvien/CV/show.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/sinhvien/CV/show.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/pages/sinhvien/CV/show.jsp(17,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg1!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      			<div class=\"alert alert-success alert-dismissible mt-3\">\r\n");
          out.write("      			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
          out.write("      				");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" \r\n");
          out.write("      			</div>\r\n");
          out.write("    	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/pages/sinhvien/CV/show.jsp(23,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg2!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      			<div class=\"alert alert-danger alert-dismissible mt-3\">\r\n");
          out.write("      			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
          out.write("      				");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" \r\n");
          out.write("      			</div>\r\n");
          out.write("    	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
