/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-05-20 16:29:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.doanhnghiep;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dangky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/TuyenDung/KHOALUAN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TuyenDungSV/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1649851804832L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/TuyenDung/KHOALUAN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TuyenDungSV/WEB-INF/lib/spring-webmvc-5.1.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1550010812000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.1.5.RELEASE.jar", Long.valueOf(1649851695791L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		.modal-dialog{\r\n");
      out.write("			max-width: 1300px;\r\n");
      out.write("		}\r\n");
      out.write("		.modal-body{\r\n");
      out.write("			margin: 20px 77px ;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"bg\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/layout/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("    <div style=\"height:70px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    	<div style=\"height:20px;\">\r\n");
      out.write("    	</div>\r\n");
      out.write("        <form class=\"row \" method=\"post\" onsubmit=\"return checkEmailDangNhap();\" action=\"/doanhnghiep/dangky\" enctype=\"multipart/form-data\">\r\n");
      out.write("          <h3 style=\"color: rgb(6, 109, 70);\" class=\"mb-5\">Đăng ký tài khoản doanh nghiệp</h3>\r\n");
      out.write("          <!-- Thong tin dang nhap -->\r\n");
      out.write("          <div class=\"mb-4 mySlides\" >\r\n");
      out.write("            <h5 class=\"mb-3\">Thông tin đăng nhập</h5>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"email\" class=\"col-sm-2 col-form-label\" >Email đăng nhập<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-10\">\r\n");
      out.write("                <input type=\"email\" class=\"form-control\" id=\"email\" name=\"txtEmail\">\r\n");
      out.write("                <small id=\"errorEmail\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"password\" class=\"col-sm-2 col-form-label\">Mật khẩu<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-10\">\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"password\" name=\"txtMatKhau\" >\r\n");
      out.write("                <small><i><b>Lưu ý: </b>Mật khẩu tối thiểu 8 ký tự, trong đó có ít nhất 1 ký tự chữ thường, 1 ký tự chữ hoa và 1 ký tự số.</i></small>\r\n");
      out.write("                <br><small id=\"errorPassword\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"rePassword\" class=\"col-sm-2 col-form-label\">Xác nhận mật khẩu<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-10\">\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"rePassword\">\r\n");
      out.write("                <small id=\"errorRePassword\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <div class=\"col-sm-10 offset-sm-2\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary\" onclick=\"validateThongTinDangNhap()\">Tiếp <i class=\"fas fa-arrow-right\"></i></button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- thong tin lien he -->\r\n");
      out.write("          <div class=\"mb-4 mySlides\" style=\"display: none;\">\r\n");
      out.write("            <h5 class=\"mb-3\">Thông tin liên hệ</h5>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"contactName\" class=\"col-sm-2 col-form-label\" >Tên người liên hệ<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-10\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"contactName\" name=\"txtTenLienHe\" >\r\n");
      out.write("                <small id=\"errorContactName\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"contactEmail\" class=\"col-sm-2 col-form-label\">Email liên hệ<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-10\">\r\n");
      out.write("                <input type=\"email\" class=\"form-control\" id=\"contactEmail\" name=\"txtEmailLienHe\" >\r\n");
      out.write("                <small id=\"errorContactEmail\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"contactTel\" class=\"col-sm-2 col-form-label\">Điện thoại<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-10\">\r\n");
      out.write("                <input type=\"tel\" class=\"form-control\" id=\"contactTel\" name=\"txtSoDienThoai\"  placeholder=\"0376551445\" >\r\n");
      out.write("                <small><i><b>Lưu ý: </b>Các thuê bao di động đã chuyển về 10 số. Vui lòng nhập thông tin theo đầu số mới.</i></small>\r\n");
      out.write("                <br><small id=\"errorContactTel\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <div class=\"col-sm-10 offset-sm-2\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary\" style=\"margin-right: 10px;\" onclick=\"currentSlide(0)\"><i class=\"fas fa-arrow-left\"></i> Trở lại </button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary\"onclick=\"validateThongTinLienHe()\">Tiếp <i class=\"fas fa-arrow-right\"></i></button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- thong tin doanh nghiep -->\r\n");
      out.write("          <div class=\"mb-4 mySlides\" style=\"display: none;\">\r\n");
      out.write("            <h5 class=\"mb-3\">Thông tin doanh nghiệp</h5>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"enterpriseName\" class=\"col-sm-3 col-form-label\" >Tên pháp lý của doanh nghiệp<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"enterpriseName\" name=\"txtTenDoanhNghiep\">\r\n");
      out.write("                <small id=\"errorEnterpriseName\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"taxCode\" class=\"col-sm-3 col-form-label\">Mã số thuế<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"taxCode\" name=\"txtMaSoThue\" >\r\n");
      out.write("                <small id=\"errorTaxCode\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"city\" class=\"col-sm-3 col-form-label\">Chọn Tỉnh/Thành phố<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <select class=\"form-select\" aria-label=\"Default select example\" id=\"city\" name=\"cmbTinhThanh\" onchange=\"setQuanHuyen()\">\r\n");
      out.write("	        		<option disabled selected value=\"\">----------</option>\r\n");
      out.write("	        		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	        		\r\n");
      out.write("                </select>\r\n");
      out.write("                <small id=\"errorCity\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"district\" class=\"col-sm-3 col-form-label\">Chọn Quận/Huyện<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <select class=\"form-select\" aria-label=\"Default select example\" id=\"district\" name=\"cmbQuanHuyen\" onchange=\"setXaPhuong()\">              \r\n");
      out.write("                	<option disabled selected value=\"\">----------</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <small id=\"errorDistrict\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"ward\" class=\"col-sm-3 col-form-label\">Chọn Xã/Phường/Thị trấn<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <select class=\"form-select\" aria-label=\"Default select example\" id=\"ward\" name=\"cmbXaPhuong\" > \r\n");
      out.write("                	\r\n");
      out.write("                </select>\r\n");
      out.write("                <small id=\"errorWard\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"street\" class=\"col-sm-3 col-form-label\">Địa chỉ đường<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"street\" name=\"txtDiaChiDuong\">\r\n");
      out.write("                <small id=\"errorStreet\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"field\" class=\"col-sm-3 col-form-label\">Chọn lĩnh vực hoạt động<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <select class=\"form-select\" aria-label=\"Default select example\" id=\"field\" name=\"cmbLinhVucHoatDong\" >\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("                <small id=\"errorField\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"enterpriseType\" class=\"col-sm-3 col-form-label\">Chọn loại hình doanh nghiệp<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <select class=\"form-select\" aria-label=\"Default select example\" id=\"enterpriseType\" name=\"cmbLoaiHinhDoanhNghiep\" required=\"required\">\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("                <small id=\"errorEnterpriseType\" style=\"color: red;\"></small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <div class=\"col-sm-9 offset-sm-3\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary\" style=\"margin-right: 10px;\" onclick=\"currentSlide(1)\"><i class=\"fas fa-arrow-left\"></i> Trở lại </button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary\" onclick=\"validateThongTinDoanhNghiep()\">Tiếp <i class=\"fas fa-arrow-right\"></i></button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"mb-4 mySlides\" style=\"display: none;\">  \r\n");
      out.write("            <h5 class=\"mb-3\">Chứng minh doanh nghiệp</h5>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("              <label for=\"certificate\" class=\"col-sm-6 col-form-label\">Tải lên giấy phép kinh doanh/Giấy chứng nhận thành lập công ty/Giấy chứng nhận đăng ký thuế của doanh nghiệp<span class=\"required\"> *</span></label>\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <input class=\"form-control\" type=\"file\" id=\"certificate\" multiple required=\"required\" name=\"giayChungNhan\" accept=\"image/*\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          <div class=\"row mb-3\">\r\n");
      out.write("            <div class=\"col-sm-11 offset-sm-1\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-outline-secondary\" style=\"margin-right: 10px;\" onclick=\"currentSlide(2)\"><i class=\"fas fa-arrow-left\"></i> Trở lại </button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- button Dangky -->\r\n");
      out.write("          <div class=\"row mb-3\"> \r\n");
      out.write("            <div class=\"col-sm-11 offset-sm-1\">\r\n");
      out.write("              <small><i>Bằng việc nhấn nút Đăng ký, Quý khách đã đồng ý với <a href=\"\" data-bs-toggle=\"modal\" data-bs-target=\"#myModalDieuKhoanDichVu\">điều khoản dịch vụ</a> của chúng tôi.</i></small>  \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      \r\n");
      out.write("          <div class=\"alert alert-danger alert-dismissible mt-3 d-none\" id=\"msgCheckEmail\">\r\n");
      out.write("      			\r\n");
      out.write("      				Email đăng nhập đã tồn tại. Vui lòng chọn email khác.\r\n");
      out.write("      	</div>\r\n");
      out.write("          <div class=\"row mb-3\">\r\n");
      out.write("            <div class=\"col-sm-11 offset-sm-1\">\r\n");
      out.write("              <button type=\"submit\"  class=\"btn btn-primary\">Đăng ký</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/layout/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- The Modal -->\r\n");
      out.write("		        <div class=\"modal\" id=\"myModalDieuKhoanDichVu\">\r\n");
      out.write("		            <div class=\"modal-dialog\">\r\n");
      out.write("		                <div class=\"modal-content\">\r\n");
      out.write("		\r\n");
      out.write("		                    <!-- Modal Header -->\r\n");
      out.write("		                    <div class=\"modal-header\">\r\n");
      out.write("		                        <h4 class=\"modal-title\">ĐIỀU KHOẢN SỬ DỤNG DỊCH VỤ VỚI DOANH NGHIỆP</h4>\r\n");
      out.write("		                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		\r\n");
      out.write("		                    <!-- Modal body -->\r\n");
      out.write("		                    <div class=\"modal-body\">\r\n");
      out.write("		                    	<h3>1. ĐIỀU KHOẢN CHUNG</h3>\r\n");
      out.write("		                    	<p>Bằng cách truy cập hoặc sử dụng trang web, các dịch vụ do trang web cung cấp, dù truy cập bằng cách nào, \r\n");
      out.write("		                    	bạn đồng ý chịu sự ràng buộc của các điều khoản sử dụng này \r\n");
      out.write("		                    	(\"Điều khoản sử dụng\").Các Điều khoản sử dụng này ảnh hưởng đến quyền và \r\n");
      out.write("		                    	nghĩa vụ pháp lý của bạn. Nếu bạn không đồng ý chịu sự ràng buộc của tất cả các Điều khoản sử dụng này, bạn không \r\n");
      out.write("		                    	truy cập hay sử dụng Dịch vụ. Nếu Bạn có bất kỳ câu hỏi nào liên quan đến Điều Khoản này, vui lòng liên hệ chúng \r\n");
      out.write("		                    	tôi tại email: ketnoidoanhnghiepdhkh@gmail.com </p>\r\n");
      out.write("\r\n");
      out.write("								<p>Chúng tôi có thể cập nhật Điều Khoản này theo thời gian vì các lý do pháp \r\n");
      out.write("								lý hoặc theo quy định hoặc để cho phép hoạt động thích hợp của trang web. \r\n");
      out.write("								Mọi thay đổi sẽ được thông báo tới bạn bằng một thông báo phù hợp trên trang web của chúng tôi. \r\n");
      out.write("								Những thay đổi này sẽ áp dụng cho việc sử dụng trang web. Sau khi chúng tôi đã thông báo đến bạn, \r\n");
      out.write("								Nếu bạn không muốn chấp nhận Điều Khoản mới, bạn không nên tiếp tục sử dụng trang web. \r\n");
      out.write("								Nếu bạn tiếp tục sử dụng trang web kể từ ngày sự thay đổi có hiệu lực, việc sử dụng trang web \r\n");
      out.write("								thể hiện bạn đồng ý bị ràng buộc bởi Điều Khoản mới.</p>\r\n");
      out.write("								<h3 class=\"mt-5\">2. ĐỊNH NGHĨA VÀ GIẢI THÍCH</h3>\r\n");
      out.write("								<ol>\r\n");
      out.write("									<li>\"<b>Trang web</b>\" chỉ hệ thống trang web kết nối doanh nghiệp và sinh viên này.</li>\r\n");
      out.write("									\r\n");
      out.write("								</ol>\r\n");
      out.write("		                    	<h3 class=\"mt-5\">3. ĐĂNG KÝ</h3>\r\n");
      out.write("		                    	<p>Để sử dụng Dịch vụ bạn phải tạo một tài khoản theo yêu cầu của trang web, bạn cam kết \r\n");
      out.write("		                    	rằng việc sử dụng tài khoản phải tuân thủ các quy định của trang web, đồng thời tất cả các thông tin bạn cung cấp cho chúng \r\n");
      out.write("		                    	tôi là đúng, chính xác, đầy đủ với tại thời điểm được yêu cầu. Mọi quyền lợi và nghĩa vụ của bạn sẽ căn cứ trên thông tin \r\n");
      out.write("		                    	tài khoản bạn đã đăng ký, do đó nếu có bất kỳ thông tin sai \r\n");
      out.write("		                    	lệch nào chúng tôi sẽ không chịu trách nhiệm trong trường hợp thông tin đó làm ảnh hưởng hoặc hạn chế quyền lợi của bạn.</p>\r\n");
      out.write("		                    	<h3 class=\"mt-5\">4. MẬT KHẨU VÀ BẢO MẬT</h3>\r\n");
      out.write("		                    	<ol>\r\n");
      out.write("		                    		<li>Khi bạn đăng ký sử dụng trang web bạn sẽ được yêu cầu khởi tạo mật khẩu. Để tránh việc gian lận, \r\n");
      out.write("		                    		bạn phải giữ mật khẩu này bảo mật và không được tiết lộ hoặc chia sẻ với bất kỳ người nào.Nếu bạn biết hoặc \r\n");
      out.write("		                    		nghi ngờ người khác biết mật khẩu của bạn, \r\n");
      out.write("		                    		bạn nên thông báo với chúng tôi ngay lập tức bằng cách liên hệ với chúng tôi tại email ketnoidoanhnghiepdhkh@gmail.com</li>\r\n");
      out.write("		                    		<li>Nếu chúng tôi có lý do để tin rằng có khả năng có hành vi vi phạm bảo mật hoặc sử dụng không đúng mục đích trang web, \r\n");
      out.write("		                    		chúng tôi có thể yêu cầu bạn thay đổi mật khẩu hoặc chúng tôi có thể tạm dừng tài khoản của bạn.</li>\r\n");
      out.write("		  							<li>Trường hợp bạn mất Mật khẩu hoặc hoặc sử dụng không đúng mục đích trang web:\r\n");
      out.write("		  									<ul style=\"list-style-type: none;\">\r\n");
      out.write("		  										<li>\r\n");
      out.write("												Bạn phải chịu tất cả sự mất mát hoặc thiệt hại phát sinh; và</li>\r\n");
      out.write("												<li>\r\n");
      out.write("												Bạn chịu trách nhiệm sẽ bồi thường hoàn toàn cho trang web trong trường hợp trang web có xảy ra mất mát hoặc thiệt hại.</li>\r\n");
      out.write("		                    				\r\n");
      out.write("		                    				</ul>\r\n");
      out.write("		                    				</li>\r\n");
      out.write("		                    	</ol>\r\n");
      out.write("		                    	<h3 class=\"mt-5\">5. QUYỀN TRUY CẬP VÀ THU THẬP THÔNG TIN</h3>\r\n");
      out.write("		                    	<ol>\r\n");
      out.write("		                    		<li>Khi sử dụng trang web, bạn thừa nhận rằng chúng tôi có quyền thu thập các thông tin sau của bạn:\r\n");
      out.write("		                    			<ul>\r\n");
      out.write("		                    				<li>Thông tin liên hệ: bao gồm các thông tin bạn cung cấp cho chúng tôi để liên hệ như tên, số điện thoại, địa chỉ email;…</li>\r\n");
      out.write("		                    				<li>Thông tin xác minh doanh nghiệp: như các thông tin về tên pháp lý của doanh nghiệp; mã số thuế; hình ảnh giấy tờ xác minh;…</li>\r\n");
      out.write("		                    			</ul>\r\n");
      out.write("										\r\n");
      out.write("									</li>\r\n");
      out.write("		                    		<li>Bạn thừa nhận và đồng ý một mình chịu trách nhiệm về hình thức, \r\n");
      out.write("		                    		nội dung và tính xác thực của bất kỳ hồ sơ hoăc tài liệu nào do bạn đăng tải trên trang web, \r\n");
      out.write("		                    		đồng thời đồng ý một mình chịu trách nhiệm cho bất kỳ hệ quả nào phát sinh từ việc đăng tải này.</li>\r\n");
      out.write("		                    		\r\n");
      out.write("		                    		<li>Bạn hiểu và thừa nhận rằng thông tin liên hệ do bạn cung cấp, sẽ được công bố cho các sinh viên và tài khoản khách trên website.</li>\r\n");
      out.write("		                    		<li>Trang web có quyền xỏa tài khoản và tất cả thông tin của bạn sau một thời gian dài không hoạt động.</li>\r\n");
      out.write("		                    		\r\n");
      out.write("		                    	</ol>\r\n");
      out.write("		                    	<h3 class=\"mt-5\">6. TUYÊN BỐ MIỄN TRỪ TRÁCH NHIỆM</h3>\r\n");
      out.write("		                    	<ol>\r\n");
      out.write("		                    		<li>Chúng tôi không tuyên bố hay đảm bảo rằng dịch vụ sẽ không bị lỗi hay không bị gián đoạn; \r\n");
      out.write("		                    		rằng các lỗi sẽ được khắc phục; hoặc rằng dịch vụ hoặc máy chủ cung cấp dịch vụ không bị nhiễm bất kỳ thành phần \r\n");
      out.write("		                    		có hại nào, bao gồm nhưng không giới hạn ở vi-rút. Chúng tôi không đưa ra bất kỳ tuyên bố hay đảm bảo nào rằng thông tin \r\n");
      out.write("		                    		(bao gồm mọi hướng dẫn) về dịch vụ chính xác, đầy đủ hoặc hữu ích. Bạn xác nhận rằng bạn tự chịu rủi ro khi sử dụng dịch vụ. \r\n");
      out.write("		                    		Trang web không đảm bảo rằng việc bạn sử dụng dịch vụ là hợp pháp trong bất kỳ khu vực pháp lý cụ thể nào và chúng tôi \r\n");
      out.write("		                    		từ chối đưa ra các bảo đảm đó một cách cụ thể. Một số khu vực pháp lý giới hạn hoặc không cho phép tuyên bố miễn \r\n");
      out.write("		                    		trừ trách nhiệm về bảo đảm ngụ ý hay các bảo đảm khác, vì vậy tuyên bố miễn trừ trách nhiệm trên có thể không áp \r\n");
      out.write("		                    		dụng cho bạn trong phạm vi luật pháp của khu vực pháp lý đó áp dụng cho bạn và các điều khoản sử dụng này. </li>\r\n");
      out.write("		                    	</ol>\r\n");
      out.write("		                    	<h3 class=\"mt-5\">7. HIỆU LỰC THỎA THUẬN CỦA HỢP ĐỒNG</h3>\r\n");
      out.write("		                    	<ol>	\r\n");
      out.write("		                    		<li>Các điều khoản quy định tại Quy định sử dụng này có thể được cập nhật, chỉnh sửa bất cứ lúc nào mà không \r\n");
      out.write("		                    		cần phải thông báo trước tới người sử dụng. Chúng tôi sẽ công bố rõ trên Website, về những thay đổi, bổ sung đó.</li>\r\n");
      out.write("		                   			<li>Trong trường hợp một hoặc một số điều khoản Quy định sử dụng này xung đột với các quy định của luật pháp và bị Tòa án tuyên là vô hiệu, \r\n");
      out.write("		                   			điều khoản đó sẽ được chỉnh sửa cho phù hợp với quy định pháp luật hiện hành, và phần còn lại của Quy định sử dụng vẫn giữ nguyên giá trị.</li>\r\n");
      out.write("		                    		<li>Thỏa thuận này có giá trị như Hợp Đồng. Doanh Nghiệp hiểu rằng, đây là hợp đồng điện tử, \r\n");
      out.write("		                    		Giá trị pháp lý của hợp đồng điện tử không thể bị phủ nhận chỉ vì hợp đồng đó được thể hiện \r\n");
      out.write("		                    		dưới dạng thông điệp dữ liệu theo Pháp Luật về Giao Dịch Điện Tử. Bằng cách đọc và chấp nhận đăng ký, \r\n");
      out.write("		                    		Doanh Nghiệp hoàn toàn đồng ý và đã hiểu các điều khoản trong Hợp Đồng này và Hợp Đồng có hiệu lực kề từ thời điểm này. \r\n");
      out.write("		                    		Nếu vi phạm các Điều khoản này, bạn đồng ý chịu hoàn toàn trách nhiệm và bồi thường thiệt hại (Nếu có) với Trang web.</li>\r\n");
      out.write("		                    	</ol>\r\n");
      out.write("		                    	<h3 class=\"mt-5\">THÔNG TIN LIÊN LẠC</h3>\r\n");
      out.write("		                    	<p>Nếu bạn có câu hỏi về Điều khoản sử dụng này, vui lòng gửi email tới địa chỉ ketnoidoanhnghiepdhkh@gmail.com để được giải đáp nhanh nhất.</p>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		\r\n");
      out.write("		                    <!-- Modal footer -->\r\n");
      out.write("		                    <div class=\"modal-footer\">\r\n");
      out.write("		                        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		\r\n");
      out.write("		                </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write(" <!-- The Modal -->\r\n");
      out.write("		        <div class=\"modal\" id=\"myModalChinhSachBaoMat\">\r\n");
      out.write("		            <div class=\"modal-dialog\">\r\n");
      out.write("		                <div class=\"modal-content\">\r\n");
      out.write("		\r\n");
      out.write("		                    <!-- Modal Header -->\r\n");
      out.write("		                    <div class=\"modal-header\">\r\n");
      out.write("		                        <h4 class=\"modal-title\">Danh sách sinh viên ứng tuyển</h4>\r\n");
      out.write("		                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		\r\n");
      out.write("		                    <!-- Modal body -->\r\n");
      out.write("		                    <div class=\"modal-body\">\r\n");
      out.write("		                    	<span style=\"color: #c0c0c0;\">Chưa có đăng ký nào</span>\r\n");
      out.write("		                    \r\n");
      out.write("		                    \r\n");
      out.write("		                    </div>\r\n");
      out.write("		\r\n");
      out.write("		                    <!-- Modal footer -->\r\n");
      out.write("		                    <div class=\"modal-footer\">\r\n");
      out.write("		                        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		\r\n");
      out.write("		                </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function setQuanHuyen(){\r\n");
      out.write("	var maTinhThanh = document.getElementById(\"city\").value;\r\n");
      out.write("	document.getElementById(\"ward\").innerHTML=\"<option disabled selected>----------</option>\";\r\n");
      out.write("	$.ajax({ \r\n");
      out.write("	    type:\"post\", \r\n");
      out.write("	    url: \"/doanhnghiep/dangky/quanhuyen\", \r\n");
      out.write("	    contentType: \"application/x-www-form-urlencoded;charset=utf-8\",\r\n");
      out.write("	    data: {\r\n");
      out.write("	    	maTinhThanh: maTinhThanh,\r\n");
      out.write("	    }, \r\n");
      out.write("	    success: function(data) { \r\n");
      out.write("	    	var row = document.getElementById(\"district\");\r\n");
      out.write("	    	row.innerHTML += data;\r\n");
      out.write("	    	\r\n");
      out.write("	    },\r\n");
      out.write("	    })\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function setXaPhuong(){\r\n");
      out.write("	var maQuanHuyen = document.getElementById(\"district\").value;\r\n");
      out.write("	$.ajax({ \r\n");
      out.write("	    type:\"post\", \r\n");
      out.write("	    url: \"/doanhnghiep/dangky/xaphuong\", \r\n");
      out.write("	    contentType: \"application/x-www-form-urlencoded;charset=utf-8\",\r\n");
      out.write("	    data: {\r\n");
      out.write("	    	maQuanHuyen: maQuanHuyen,\r\n");
      out.write("	    }, \r\n");
      out.write("	    success: function(data) { \r\n");
      out.write("	    	var row = document.getElementById(\"ward\");\r\n");
      out.write("	    	row.innerHTML = data;\r\n");
      out.write("	    },\r\n");
      out.write("	    })\r\n");
      out.write("};\r\n");
      out.write("function validateThongTinDangNhap(){\r\n");
      out.write("	var kt= true;\r\n");
      out.write("	var checkEmail= /^[a-zA-Z][a-zA-Z0-9_\\.]{5,63}@[a-zA-Z0-9]{2,}(\\.[a-zA-Z0-9]{2,4}){1,2}$/;\r\n");
      out.write("	var checkPassword= /^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$/;\r\n");
      out.write("	\r\n");
      out.write("	var email = document.getElementById(\"email\").value;\r\n");
      out.write("	var password = document.getElementById(\"password\").value;\r\n");
      out.write("	var rePassword = document.getElementById(\"rePassword\").value;\r\n");
      out.write("	if(!checkEmail.test(email)) {	\r\n");
      out.write("		document.getElementById(\"errorEmail\").innerText=\"Email không hợp lệ\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorEmail\").innerText=\"\";\r\n");
      out.write("	if(!checkPassword.test(password)) {	\r\n");
      out.write("		document.getElementById(\"errorPassword\").innerText=\"Mật khẩu không hợp lệ\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorPassword\").innerText=\"\";\r\n");
      out.write("	if(rePassword!=password) {	\r\n");
      out.write("		document.getElementById(\"errorRePassword\").innerText=\"Mật khẩu không khớp\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorRePassword\").innerText=\"\";\r\n");
      out.write("	if(kt) currentSlide(1);\r\n");
      out.write("};\r\n");
      out.write("function validateThongTinLienHe(){\r\n");
      out.write("	var kt= true;\r\n");
      out.write("	var checkEmail= /^[a-zA-Z][a-zA-Z0-9_\\.]{5,63}@[a-zA-Z0-9]{2,}(\\.[a-zA-Z0-9]{2,4}){1,2}$/;\r\n");
      out.write("	var checkTel= /^0[35789][0-9]{8}$/;\r\n");
      out.write("	\r\n");
      out.write("	var contactName = document.getElementById(\"contactName\").value;\r\n");
      out.write("	var contactEmail = document.getElementById(\"contactEmail\").value;\r\n");
      out.write("	var contactTel = document.getElementById(\"contactTel\").value;\r\n");
      out.write("	if(!checkEmail.test(contactEmail)) {	\r\n");
      out.write("		document.getElementById(\"errorContactEmail\").innerText=\"Email không hợp lệ\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorContactEmail\").innerText=\"\";\r\n");
      out.write("	if(!checkTel.test(contactTel)) {	\r\n");
      out.write("		document.getElementById(\"errorContactTel\").innerText=\"Số điện thoại không hợp lệ\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorContactTel\").innerText=\"\";\r\n");
      out.write("	if(contactName==\"\") {	\r\n");
      out.write("		document.getElementById(\"errorContactName\").innerText=\"Tên người liên hệ không được bỏ trống\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorContactName\").innerText=\"\";\r\n");
      out.write("	if(kt) currentSlide(2);\r\n");
      out.write("};\r\n");
      out.write("function validateThongTinDoanhNghiep(){\r\n");
      out.write("	var kt= true;\r\n");
      out.write("	var checkTaxCode= /^([0-9]{10}|[0-9]{13})$/;\r\n");
      out.write("	\r\n");
      out.write("	var enterpriseName = document.getElementById(\"enterpriseName\").value;\r\n");
      out.write("	var taxCode = document.getElementById(\"taxCode\").value;\r\n");
      out.write("	var city = document.getElementById(\"city\").value;\r\n");
      out.write("	var district = document.getElementById(\"district\").value;\r\n");
      out.write("	var ward = document.getElementById(\"ward\").value;\r\n");
      out.write("	var street = document.getElementById(\"street\").value;\r\n");
      out.write("	var field = document.getElementById(\"field\").value;\r\n");
      out.write("	var enterpriseType = document.getElementById(\"enterpriseType\").value;\r\n");
      out.write("	\r\n");
      out.write("	console.log(city);\r\n");
      out.write("	if(enterpriseName==\"\"){\r\n");
      out.write("		document.getElementById(\"errorEnterpriseName\").innerText=\"Tên doanh nghiệp không được bỏ trống\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else  document.getElementById(\"errorEnterpriseName\").innerText=\"\";\r\n");
      out.write("	if(!checkTaxCode.test(taxCode)) {	\r\n");
      out.write("		document.getElementById(\"errorTaxCode\").innerText=\"Mã số thuế không hợp lệ\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorTaxCode\").innerText=\"\";\r\n");
      out.write("	if(city==\"\"){\r\n");
      out.write("		document.getElementById(\"errorCity\").innerText=\"Tỉnh/Thành phố không được bỏ trống\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else  document.getElementById(\"errorCity\").innerText=\"\";\r\n");
      out.write("	if(district==\"\"){\r\n");
      out.write("		document.getElementById(\"errorDistrict\").innerText=\"Quận/huyện không được bỏ trống\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorDistrict\").innerText=\"\";\r\n");
      out.write("	if(ward==\"\"){\r\n");
      out.write("		document.getElementById(\"errorWard\").innerText=\"Xã/phường/thị trấn không được bỏ trống\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorWard\").innerText=\"\";\r\n");
      out.write("	if(street==\"\"){\r\n");
      out.write("		document.getElementById(\"errorStreet\").innerText=\"Địa chỉ đường không được bỏ trống\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorStreet\").innerText=\"\";\r\n");
      out.write("	if(field==\"\"){\r\n");
      out.write("		document.getElementById(\"errorField\").innerText=\"Lĩnh vực hoạt động không được bỏ trống\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorField\").innerText=\"\";\r\n");
      out.write("	if(enterpriseType==\"\"){\r\n");
      out.write("		document.getElementById(\"errorEnterpriseType\").innerText=\"Loại hình doanh nghiệp không được bỏ trống\";\r\n");
      out.write("		kt=false;\r\n");
      out.write("	}\r\n");
      out.write("	else document.getElementById(\"errorEnterpriseType\").innerText=\"\";\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	if(kt) currentSlide(3);\r\n");
      out.write("};\r\n");
      out.write("function checkEmailDangNhap(){\r\n");
      out.write("	var email = document.getElementById(\"email\").value;\r\n");
      out.write("	var kt=false;\r\n");
      out.write("	$.ajax({ \r\n");
      out.write("	    type:\"post\", \r\n");
      out.write("	    url: \"/doanhnghiep/dangky/checkemaildangnhap\", \r\n");
      out.write("	    contentType: \"application/x-www-form-urlencoded;charset=utf-8\",\r\n");
      out.write("	    data: {\r\n");
      out.write("	    	email: email,\r\n");
      out.write("	    }, \r\n");
      out.write("	    async: false,\r\n");
      out.write("	    success: function(data) { \r\n");
      out.write("	    	console.log(data);\r\n");
      out.write("	    	var x=document.getElementById(\"msgCheckEmail\");\r\n");
      out.write("	    	if(data==\"true\"){\r\n");
      out.write("	    		x.className=\"alert alert-danger alert-dismissible mt-3 d-block\"; \r\n");
      out.write("	    		kt=false;\r\n");
      out.write("	    	}\r\n");
      out.write("	    	else {\r\n");
      out.write("	    		x.className=\"alert alert-danger alert-dismissible mt-3 d-none\";\r\n");
      out.write("	    		kt=true;\r\n");
      out.write("	    	}\r\n");
      out.write("	    },\r\n");
      out.write("	    })\r\n");
      out.write("	console.log(kt);\r\n");
      out.write("	  return kt;\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/doanhnghiep/dangky.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(119,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/doanhnghiep/dangky.jsp(119,11) '${dsTinhThanh }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dsTinhThanh }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(119,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("tt");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("	        			<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tt.getMaTinhThanh()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tt.getTenTinhThanh() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option> \r\n");
            out.write("	        		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(157,18) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/doanhnghiep/dangky.jsp(157,18) '${dsLinhVuc }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dsLinhVuc }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(157,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("lv");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                	<optgroup title=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lv.getTenLinhVuc() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" label=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lv.getTenLinhVuc() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                		");
            if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("                	</optgroup>\r\n");
            out.write("        			\r\n");
            out.write("        			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(159,18) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/doanhnghiep/dangky.jsp(159,18) '${linhVucHoatDongCap2DAO.getAllLinhVucHoatDongByIdCap1(lv.getMaLinhVuc()) }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${linhVucHoatDongCap2DAO.getAllLinhVucHoatDongByIdCap1(lv.getMaLinhVuc()) }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(159,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("lvc1");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                			<option title=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lvc1.getTenLinhVuc() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lvc1.getMaLinhVuc() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lvc1.getTenLinhVuc() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(173,18) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/doanhnghiep/dangky.jsp(173,18) '${dsLoaiHinhDoanhNghiep }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dsLoaiHinhDoanhNghiep }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/pages/doanhnghiep/dangky.jsp(173,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("lhdn");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        			<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lhdn.getMaLoaiHinhDoanhNghiep() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lhdn.getTenLoaiHinhDoanhNghiep() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("        			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }
}
